
package lt.viko.eif.rgenzuras.sb_client.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "storePort", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StorePort {


    /**
     * 
     * @param addItemRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.AddItemResponse
     */
    @WebMethod
    @WebResult(name = "addItemResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "addItemResponse")
    public AddItemResponse addItem(
        @WebParam(name = "addItemRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "addItemRequest")
        AddItemRequest addItemRequest);

    /**
     * 
     * @param addCustomerRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.AddCustomerResponse
     */
    @WebMethod
    @WebResult(name = "addCustomerResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "addCustomerResponse")
    public AddCustomerResponse addCustomer(
        @WebParam(name = "addCustomerRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "addCustomerRequest")
        AddCustomerRequest addCustomerRequest);

    /**
     * 
     * @param getCustomerRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.GetCustomerResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "getCustomerResponse")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "getCustomerRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "getCustomerRequest")
        GetCustomerRequest getCustomerRequest);

    /**
     * 
     * @param removeCustomerRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.RemoveCustomerResponse
     */
    @WebMethod
    @WebResult(name = "removeCustomerResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "removeCustomerResponse")
    public RemoveCustomerResponse removeCustomer(
        @WebParam(name = "removeCustomerRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "removeCustomerRequest")
        RemoveCustomerRequest removeCustomerRequest);

    /**
     * 
     * @param removeItemRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.RemoveItemResponse
     */
    @WebMethod
    @WebResult(name = "removeItemResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "removeItemResponse")
    public RemoveItemResponse removeItem(
        @WebParam(name = "removeItemRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "removeItemRequest")
        RemoveItemRequest removeItemRequest);

    /**
     * 
     * @param getItemRequest
     * @return
     *     returns lt.viko.eif.rgenzuras.sb_client.soap.GetItemResponse
     */
    @WebMethod
    @WebResult(name = "getItemResponse", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "getItemResponse")
    public GetItemResponse getItem(
        @WebParam(name = "getItemRequest", targetNamespace = "http://schema.sb-sample.rgenzuras.eif.viko.lt", partName = "getItemRequest")
        GetItemRequest getItemRequest);

}
